# Generated by Django 4.1.3 on 2023-04-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='confirm_password',
            new_name='confirmpassword',
        ),
    ]
